"""add users and ownership

Revision ID: a94c026f662c
Revises: 1f1ad8675ee0
Create Date: 2026-09-01 01:02:01.969584

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a94c026f662c'
down_revision: str | Sequence[str] | None = '1f1ad8675ee0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_anomalies_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_anomalies_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_subscriptions_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_uploads_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_uploads_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_uploads_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_uploads_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_anomalies_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_anomalies_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
